/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import com.util.ConnectionConfig;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author Pung's Computer
 */
public class Transaction extends javax.swing.JInternalFrame {

    /**
     * Creates new form Transaction
     */
    Connection connection = null;
    PreparedStatement preparedStatement =null;
    Statement statement=null;
    ResultSet resultSet = null;
    public Transaction() {
        initComponents();
        fillCombo();
        showDate();
        getsum();
        transaction();
        AutoCompleteDecorator.decorate(cbx_name);
        this.setLocation(0,0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jScrollBar1 = new javax.swing.JScrollBar();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txt_pay = new javax.swing.JTextField();
        txt_chane = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btn_calculate = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        ttx_Date = new javax.swing.JTextField();
        btn_print = new javax.swing.JButton();
        txt_Harga = new javax.swing.JTextField();
        txt_quantity = new javax.swing.JTextField();
        cbx_name = new javax.swing.JComboBox<>();
        btn_add = new javax.swing.JButton();
        btn_remove = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_Show = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_noBill = new javax.swing.JTextField();
        txt_idKelengkeng = new javax.swing.JTextField();
        txt_total = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(864, 546));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(851, 510));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_pay.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txt_pay.setForeground(new java.awt.Color(0, 0, 0));
        txt_pay.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_pay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_payActionPerformed(evt);
            }
        });
        jPanel1.add(txt_pay, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 440, 143, -1));

        txt_chane.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(txt_chane, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 480, 143, -1));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Change");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 490, 70, 20));

        btn_calculate.setBackground(new java.awt.Color(51, 51, 51));
        btn_calculate.setForeground(new java.awt.Color(255, 255, 255));
        btn_calculate.setText("Calculate");
        btn_calculate.setBorder(null);
        btn_calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calculateActionPerformed(evt);
            }
        });
        jPanel1.add(btn_calculate, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 430, 80, 40));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Date");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 93, -1, -1));

        ttx_Date.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        ttx_Date.setForeground(new java.awt.Color(0, 0, 0));
        ttx_Date.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(ttx_Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 89, 181, -1));

        btn_print.setBackground(new java.awt.Color(51, 51, 51));
        btn_print.setForeground(new java.awt.Color(255, 255, 255));
        btn_print.setText("Print");
        btn_print.setBorder(null);
        btn_print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_printActionPerformed(evt);
            }
        });
        jPanel1.add(btn_print, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 375, 70, 40));

        txt_Harga.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txt_Harga.setForeground(new java.awt.Color(0, 0, 0));
        txt_Harga.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(txt_Harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 273, 181, -1));

        txt_quantity.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txt_quantity.setForeground(new java.awt.Color(0, 0, 0));
        txt_quantity.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(txt_quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 318, 181, -1));

        cbx_name.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        cbx_name.setForeground(new java.awt.Color(0, 0, 0));
        cbx_name.setBorder(null);
        cbx_name.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cbx_namePopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                cbx_namePopupMenuWillBecomeVisible(evt);
            }
        });
        cbx_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_nameActionPerformed(evt);
            }
        });
        jPanel1.add(cbx_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 175, 181, -1));

        btn_add.setBackground(new java.awt.Color(51, 51, 51));
        btn_add.setForeground(new java.awt.Color(255, 255, 255));
        btn_add.setText("Add");
        btn_add.setBorder(null);
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });
        jPanel1.add(btn_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 375, 60, 40));

        btn_remove.setBackground(new java.awt.Color(51, 51, 51));
        btn_remove.setForeground(new java.awt.Color(255, 255, 255));
        btn_remove.setText("Remove");
        btn_remove.setBorder(null);
        btn_remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_removeActionPerformed(evt);
            }
        });
        jPanel1.add(btn_remove, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 375, 70, 40));

        table_Show.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Quantity", "Kelengkeng", "Price(per/kg)", "Price"
            }
        ));
        table_Show.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_ShowMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_Show);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, 411, 310));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Total");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 410, 60, 20));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Pay");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 440, 60, 30));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Bill No");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 135, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Jenis Kelengkeng");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 180, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Quantity");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 322, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Harga");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 277, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Id Kelengkeng ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 231, -1, -1));

        txt_noBill.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txt_noBill.setForeground(new java.awt.Color(0, 0, 0));
        txt_noBill.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_noBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_noBillActionPerformed(evt);
            }
        });
        jPanel1.add(txt_noBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 131, 181, -1));

        txt_idKelengkeng.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txt_idKelengkeng.setForeground(new java.awt.Color(0, 0, 0));
        txt_idKelengkeng.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(txt_idKelengkeng, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 227, 181, -1));

        txt_total.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txt_total.setForeground(new java.awt.Color(0, 0, 0));
        txt_total.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_totalActionPerformed(evt);
            }
        });
        jPanel1.add(txt_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 400, 143, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 892, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(jLabel9)
                        .addGap(232, 232, 232))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(jLabel3)
                        .addGap(350, 350, 350)
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jScrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void fillCombo(){
        String sql="select * from kelengkeng";
        try {
            connection = ConnectionConfig.getConnection();
            preparedStatement=connection.prepareCall(sql);
            resultSet = preparedStatement.executeQuery();
            while(resultSet.next()){
                String name = resultSet.getString("jenis");
                cbx_name.addItem(name);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    public static  String DateFormat = "yyyy-MM-dd";
    public void showDate(){
      Calendar cal= Calendar.getInstance();
      SimpleDateFormat format = new SimpleDateFormat(DateFormat);
      ttx_Date.setText(format.format(cal.getTime()));
    }
    public void transaction(){
        String sql = "select count(*) from transaksi";
        try {
            connection = ConnectionConfig.getConnection();
            preparedStatement=connection.prepareStatement(sql);
            resultSet=preparedStatement.executeQuery();
            while(resultSet.next()){
                int g=Integer.parseInt(resultSet.getString(1));
                g=g+1;
                txt_noBill.setText(String.valueOf(g));
            }
        } catch (Exception e) {
        }
    }
    private void txt_noBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_noBillActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_noBillActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel model =(DefaultTableModel) table_Show.getModel();
        String s1 = txt_Harga.getText();
        String s2 = txt_quantity.getText();
        
        int a = Integer.parseInt(s1);
        double b = Double.parseDouble(s2);
        double c = a*b;
        
        String result = String.valueOf(c);
        model.addRow(new Object[]{txt_quantity.getText(),txt_Harga.getText(),cbx_name.getSelectedItem(),result});
        getsum();
    }//GEN-LAST:event_btn_addActionPerformed
    public void getsum(){
        double sum=0;
          for(int i=0; i < table_Show.getRowCount(); i++){
              sum = sum + Double.parseDouble(table_Show.getValueAt(i,3).toString());
          }
          txt_total.setText(Double.toString(sum));
    }
    
    public void transactionUpdate(){
        String kelengkeng = (String) cbx_name.getSelectedItem();
        String sql = "insert into transaksi(id,kelengkeng,harga_bayar,jumlah,tanggal) "
                + "Values ("+txt_noBill.getText()+",'"+kelengkeng+"',"+txt_total.getText()+","+txt_quantity.getText()+",'"+ttx_Date.getText()+"')";
        try {
            connection = ConnectionConfig.getConnection();
            statement = connection.createStatement();
            statement.execute(sql);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
    }
    private void txt_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_totalActionPerformed

    private void btn_printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_printActionPerformed
        // TODO add your handling code here:
        transactionUpdate();
      
        MessageFormat header=new MessageFormat("User Report");
        MessageFormat footer=new MessageFormat("Page{0,number,integer}");
        
        try{
            table_Show.print(JTable.PrintMode.NORMAL, header, footer );
        }
        catch(java.awt.print.PrinterException e){
            System.err.format("Cannot print %%n",e.getMessage());
        }
    }//GEN-LAST:event_btn_printActionPerformed

    private void btn_calculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calculateActionPerformed
        // TODO add your handling code here:
        transactionUpdate();
        String s = txt_total.getText();
        String s1 = txt_pay.getText();
        
        double a = Double.parseDouble(s);
        double b = Double.parseDouble(s1);
        double c = b-a;
        
        String result = String.valueOf(c);
        txt_chane.setText(result);
        
    }//GEN-LAST:event_btn_calculateActionPerformed

    private void table_ShowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_ShowMouseClicked
        // TODO add your handling code here:
       DefaultTableModel model =(DefaultTableModel) table_Show.getModel();
      txt_quantity.setText(model.getValueAt( table_Show.getSelectedRow(), 0).toString());
      txt_Harga.setText(model.getValueAt( table_Show.getSelectedRow(), 1).toString());
    }//GEN-LAST:event_table_ShowMouseClicked

    private void cbx_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_nameActionPerformed

    private void cbx_namePopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cbx_namePopupMenuWillBecomeVisible
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_namePopupMenuWillBecomeVisible

    private void cbx_namePopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cbx_namePopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        String temp = (String) cbx_name.getSelectedItem();
        String sql = "select * from kelengkeng where jenis=?";
        try {
            connection=ConnectionConfig.getConnection();
            preparedStatement=connection.prepareStatement(sql);
            preparedStatement.setString(1, temp);
            resultSet=preparedStatement.executeQuery();
            if(resultSet.next()){
                String add=resultSet.getString("id");
                txt_idKelengkeng.setText(add);
                String add1 = resultSet.getString("harga");
                txt_Harga.setText(add1);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_cbx_namePopupMenuWillBecomeInvisible

    private void btn_removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_removeActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model =(DefaultTableModel) table_Show.getModel();
        model.removeRow(table_Show.getSelectedRow());
            
    }//GEN-LAST:event_btn_removeActionPerformed

    private void txt_payActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_payActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_payActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_calculate;
    private javax.swing.JButton btn_print;
    private javax.swing.JButton btn_remove;
    private javax.swing.JComboBox<String> cbx_name;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_Show;
    private javax.swing.JTextField ttx_Date;
    private javax.swing.JTextField txt_Harga;
    private javax.swing.JTextField txt_chane;
    private javax.swing.JTextField txt_idKelengkeng;
    private javax.swing.JTextField txt_noBill;
    private javax.swing.JTextField txt_pay;
    private javax.swing.JTextField txt_quantity;
    private javax.swing.JTextField txt_total;
    // End of variables declaration//GEN-END:variables
}
