/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import com.entities.Kelengkeng;
import com.util.ConnectionConfig;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Pung's Computer
 */
public class Update_stock extends javax.swing.JInternalFrame {

    /**
     * Creates new form Update_stock
     */
    public Update_stock() {
        initComponents();
        show_stock();
        this.setLocation(0,0);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_update = new javax.swing.JButton();
        btn_new = new javax.swing.JButton();
        txt_idKel = new javax.swing.JTextField();
        txt_jenisKel = new javax.swing.JTextField();
        txt_harga = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btn_delete = new javax.swing.JButton();

        setBackground(new java.awt.Color(38, 38, 38));
        setBorder(null);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(864, 546));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Id Kelengekeng");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 165, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Jenis Kelengkeng");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 213, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Harga");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 266, -1, -1));

        btn_update.setBackground(new java.awt.Color(51, 51, 51));
        btn_update.setForeground(new java.awt.Color(255, 255, 255));
        btn_update.setText("Update");
        btn_update.setBorder(null);
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });
        jPanel1.add(btn_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 320, 70, 40));

        btn_new.setBackground(new java.awt.Color(51, 51, 51));
        btn_new.setForeground(new java.awt.Color(255, 255, 255));
        btn_new.setText("New");
        btn_new.setBorder(null);
        btn_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_newActionPerformed(evt);
            }
        });
        jPanel1.add(btn_new, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 66, 40));

        txt_idKel.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txt_idKel.setForeground(new java.awt.Color(0, 0, 0));
        txt_idKel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_idKel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idKelActionPerformed(evt);
            }
        });
        jPanel1.add(txt_idKel, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 164, 112, -1));

        txt_jenisKel.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txt_jenisKel.setForeground(new java.awt.Color(0, 0, 0));
        txt_jenisKel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(txt_jenisKel, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 212, 112, -1));

        txt_harga.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txt_harga.setForeground(new java.awt.Color(0, 0, 0));
        txt_harga.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(txt_harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 265, 112, -1));

        jTable1.setBackground(new java.awt.Color(51, 51, 51));
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id_kelengkeng", "jenis_kelengkeng", "harga"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 33, -1, 348));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Update Stock");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 55, 111, 51));

        btn_delete.setBackground(new java.awt.Color(51, 51, 51));
        btn_delete.setForeground(new java.awt.Color(255, 255, 255));
        btn_delete.setText("Delete");
        btn_delete.setBorder(null);
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });
        jPanel1.add(btn_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 320, 70, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 864, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_idKelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idKelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idKelActionPerformed

    private void btn_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_newActionPerformed
        // TODO add your handling code here:
        String query="insert into kelengkeng (id,jenis,harga) "
                + "VALUES("+txt_idKel.getText()+",'"+txt_jenisKel.getText()+"',"+txt_harga.getText()+");";
             executeSQlQuery(query,"INSERTED");
        
      
    }//GEN-LAST:event_btn_newActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
    int i=jTable1.getSelectedRow();
    TableModel model=jTable1.getModel();
    txt_idKel.setText(model.getValueAt(i, 0).toString());
    txt_jenisKel.setText(model.getValueAt(i, 1).toString());
    txt_harga.setText(model.getValueAt(i, 2).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        // TODO add your handling code here:           
        String query = "UPDATE kelengkeng SET jenis='"+txt_jenisKel.getText()+"',harga="+txt_harga.getText()+" WHERE id = "+txt_idKel.getText();
        executeSQlQuery(query,"Updated");
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
        String query="DELETE From kelengkeng where id="+txt_idKel.getText();
        executeSQlQuery(query, "Deleted");
    }//GEN-LAST:event_btn_deleteActionPerformed

    /**
     * @param args the command line arguments
     */
    Connection connection = null;
    PreparedStatement preparedStatement =null;
    ResultSet resultSet = null;
    Statement statement = null;
    
    public ArrayList<Kelengkeng>getStock(){
        ArrayList<Kelengkeng> stockKelengkeng = new ArrayList<Kelengkeng>();
        connection = ConnectionConfig.getConnection();
        String sql = "select * from kelengkeng;";
        try {
            statement=connection.createStatement();
            resultSet=statement.executeQuery(sql);
            Kelengkeng kelengkeng;
            while (resultSet.next()){
                kelengkeng = new Kelengkeng(resultSet.getInt("id"),resultSet.getString("jenis"),resultSet.getDouble("harga"));
                stockKelengkeng.add(kelengkeng);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return stockKelengkeng;
    }
    
    public void show_stock(){
        ArrayList<Kelengkeng> list = getStock();
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        Object[] row = new Object[3];
        for (int i=0;i<list.size();i++){
            row[0]=list.get(i).getId_kelengkeng();
            row[1]=list.get(i).getJenis_kelengkeng();
            row[2]=list.get(i).getHarga();
            model.addRow(row);
        }
    }
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Update_stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Update_stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Update_stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Update_stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Update_stock().setVisible(true);
//            }
//        });
//    }
    public void executeSQlQuery(String query, String message){
       Connection connection = ConnectionConfig.getConnection();
       Statement statement;
       try{
           statement = connection.createStatement();
           if((statement.executeUpdate(query)) == 1)
           {
               DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
               model.setRowCount(0);
               show_stock();
               txt_idKel.setText("");
               txt_jenisKel.setText("");
               txt_harga.setText("");
               JOptionPane.showMessageDialog(null, "Data "+message+" Succefully");
           }else{
               JOptionPane.showMessageDialog(null, "Data Not "+message);
           }
       }catch(Exception e){
           e.printStackTrace();
       }
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_new;
    private javax.swing.JButton btn_update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txt_harga;
    private javax.swing.JTextField txt_idKel;
    private javax.swing.JTextField txt_jenisKel;
    // End of variables declaration//GEN-END:variables
}
